export const CREATE_COMMENT_PENDING = "CREATE_COMMENT_PENDING";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";

export const DELETE_COMMENT_PENDING = "DELETE_COMMENT_PENDING";
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";

export const EDIT_COMMENT_PENDING = "EDIT_COMMENT_PENDING";
export const EDIT_COMMENT_FAILURE = "EDIT_COMMENT_FAILURE";
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";

export const FETCH_ALL_COMMENTS_PENDING = "FETCH_ALL_COMMENTS_PENDING";
export const FETCH_ALL_COMMENTS_FAILURE = "FETCH_ALL_COMMENTS_FAILURE";
export const FETCH_ALL_COMMENTS_SUCCESS = "FETCH_ALL_COMMENTS_SUCCESS";

export const FETCH_COMMENT_PENDING = "FETCH_COMMENT_PENDING";
export const FETCH_COMMENT_FAILURE = "FETCH_COMMENT_FAILURE";
export const FETCH_COMMENT_SUCCESS = "FETCH_COMMENT_SUCCESS";

export const VOTE_COMMENT_SUCCESS  = "VOTE_COMMENT_SUCCESS";
export const VOTE_COMMENT_FAILURE  = "VOTE_COMMENT_FAILURE";

