export const CREATE_POST_PENDING = "CREATE_POST_PENDING";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";

export const EDIT_POST_PENDING = "EDIT_POST_PENDING";
export const EDIT_POST_FAILURE = "EDIT_POST_FAILURE";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";

export const DELETE_POST_PENDING = "DELETE_POST_PENDING";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";

export const FETCH_ALL_POSTS_PENDING = "FETCH_ALL_POSTS_PENDING";
export const FETCH_ALL_POSTS_FAILURE = "FETCH_ALL_POSTS_FAILURE";
export const FETCH_ALL_POSTS_SUCCESS = "FETCH_ALL_POSTS_SUCCESS";

export const FETCH_POST_PENDING = "FETCH_POST_PENDING";
export const FETCH_POST_FAILURE = "FETCH_POST_FAILURE";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";

export const VOTE_POST_SUCCESS  = "VOTE_POST_SUCCESS";
export const VOTE_POST_FAILURE  = "VOTE_POST_FAILURE";

export const SORT_POSTS = "SORT_POSTS";
